# install-services.yml
---
  - hosts: loadbalancers
    become: true
    tasks:
      - name: Installing apache
        apt: name=httpd state=present
      - name: Ensure apache starts
        service: name=httpd state=started enabled=yes

  - hosts: webservers
    become: true
    tasks:
      - name: Installing services 
        apt:
          pkg:
            - httpd
            - php
          state: present
      - name: Ensure apache starts
        service: name=httpd state=started enabled=yes
